Expose API url variables for ghostnet & mainnet
marigold-dev/gas-station-lib pull request #5
Opened 2023-12-18 10:33 UTC by quentin-burg

And update Gas Station class constructor to accept empty parameter and add Ghostnet api URL per default

2023-12-27 11:11 UTC, aguillon requested changes
Minor changes

2023-12-27 11:11 UTC, aguillon commented on .github/workflows/docker-nft-ghostnet-staging.yml
> +          sed -i 's|KT1Rp1rgfwS25XrWU6fUnR8cw6KMZBhDvXdq|KT1K9X6QpuTWFX4S5ieDGTUdjAHQtiFRH5op|g' ./examples/nft/.env
I'm not sure why you're not changing the file directly? Is it because we're using a different account for the gas station on Ghostnet and Staging? I'm not sure it's worth it; and even then, we can change the contract to allow several admins.

2023-12-27 11:11 UTC, aguillon commented on index.ts
> +
We should remove the trailing /operation and add it in `postOperations`.

2023-12-27 11:11 UTC, aguillon commented on index.ts
> +const g = new GasStation();
Why?

2024-01-04 10:44 UTC, aguillon commented on .github/workflows/docker-nft-ghostnet-staging.yml
> +          sed -i 's|KT1Rp1rgfwS25XrWU6fUnR8cw6KMZBhDvXdq|KT1K9X6QpuTWFX4S5ieDGTUdjAHQtiFRH5op|g' ./examples/nft/.env
Or we could just originate a single contract that can have two admins, see https://github.com/aguillon/permit-cameligo/pull/3

2024-01-08 08:22 UTC, quentin-burg commented on .github/workflows/docker-nft-ghostnet-staging.yml
> +          sed -i 's|KT1Rp1rgfwS25XrWU6fUnR8cw6KMZBhDvXdq|KT1K9X6QpuTWFX4S5ieDGTUdjAHQtiFRH5op|g' ./examples/nft/.env
Yes it's because the contract has only one admin but we can deploy the contract with several admin and just remove this part after.

2024-01-25 11:26 UTC, aguillon commented
Rebasing all of this in order not to introduce a merge commit in the history

2024-01-25 11:26 UTC, merged