Minting UX
marigold-dev/gas-station-lib pull request #8
Opened 2024-01-18 12:25 UTC by lykimq

This PR contains:
- Add comments in the `index.ts` 
- Add progress bar for Mint
- Formatting code
- Add Readme
- Add Makefile
- Add ignore `*d.ts, *.js` in `.gitignore`

2024-01-19 10:04 UTC, quentin-burg approved these changes
Good ! Thanks 👍 😄

2024-01-19 10:04 UTC, quentin-burg commented on examples/nft/Makefile
Why do you need a Makefile ? 🧐 
You can just add some scripts into `package.json` and run `npm run myAwesomeCommand`

2024-01-19 10:04 UTC, quentin-burg commented on examples/nft/README.md
> +- npm (Node Package Manager): Comes with Node.js installation
You can talk about `nvm` (Node Version Manager) to manage easily Node versions : https://github.com/nvm-sh/nvm#installing-and-updating :-)

2024-01-19 10:04 UTC, quentin-burg commented on examples/nft/README.md
> +make install
or `npm i` 😉

2024-01-19 10:04 UTC, quentin-burg commented on examples/nft/src/routes/+page.svelte
> +    {#if $myAccount == undefined}
you need `===`  in Javascript, otherwise it doesn't test type

2024-01-19 11:49 UTC, lykimq commented on examples/nft/README.md
> +- npm (Node Package Manager): Comes with Node.js installation
I update the nvm at this [commit](https://github.com/marigold-dev/gas-station-lib/pull/8/commits/ed9fb0e10837aa0546c666759690ed79081b7b10)

2024-01-19 11:51 UTC, lykimq commented on examples/nft/src/routes/+page.svelte
> +    {#if $myAccount == undefined}
I add it at this [commit](https://github.com/marigold-dev/gas-station-lib/pull/8/commits/32cb02b77154073805717f22447157008b73eaef)

2024-01-19 11:51 UTC, lykimq commented on examples/nft/Makefile
I tend to forget the command run, that why :)

2024-01-19 11:52 UTC, lykimq commented on examples/nft/README.md
> +make install
I prefer to keep it as `make install`, but yes it is equivalence. :)

2024-01-20 03:50 UTC, aguillon requested changes
Hey that's great, thank you! Can you just please remove the Makefile and use the `npm` related instructions in the README instead? And add the animation to the Stash button as well please.

Also, please remove the `text-align: center;` that I added for the `main` component? I don't know what I was thinking but yikes.

2024-01-20 03:50 UTC, aguillon commented on index.ts
> + * TransferOperaiton: Represents a specific type of operation for transferring tokens,
`TransferOperaiton` is a typo

2024-01-20 03:50 UTC, aguillon commented on examples/nft/Makefile
I agree with @quentin-burg, please remove the Makefile, it is unecessary in this case.

2024-01-22 10:31 UTC, lykimq commented on examples/nft/Makefile
I have drop the commit of the Makefile and change the README as well at this [commit](https://github.com/marigold-dev/gas-station-lib/pull/8/commits/0a7ed1f260fe991c423dfcc4dd5d480ff8829c3d)

2024-01-22 10:32 UTC, lykimq commented on index.ts
> + * TransferOperaiton: Represents a specific type of operation for transferring tokens,
Thanks, correct it at this [commit](https://github.com/marigold-dev/gas-station-lib/pull/8/commits/3dff2581e3e14ed88efb2883984400bdcfb03284)

2024-01-22 10:37 UTC, lykimq commented on index.ts
> + * TransferOperaiton: Represents a specific type of operation for transferring tokens,
I remove the `text-align:center` at this [commit](https://github.com/marigold-dev/gas-station-lib/pull/8/commits/53d47f800b92b1cb0490be0281422687bafd1dde#diff-d636b144ee28938d7218a83279a6f4ea1bc7ba85f567f9269bf0841d7a0cb169L41)

2024-01-22 10:41 UTC, quentin-burg commented
Seems good for me !

2024-01-22 12:32 UTC, lykimq commented
I add the stashing progress bar at this [commit](https://github.com/marigold-dev/gas-station-lib/pull/8/commits/25648eeac8ee774ec8ab43b6c7d1d39ebf26121b)

2024-01-22 15:00 UTC, aguillon commented
Looks good thanks, let's test on staging.

2024-01-22 15:00 UTC, merged